### ISSUE TITLE
Problems with binding click GUI after compiling the client.

### ISSUE THREAD

**Issue by PilaCiu** [MOMIN5/Phobos-1.16#14]
It doesn't seem to work for some reason?
Client is compiled properly.

**Comment by goztb22** [comment]
there no clickgui ported atm i think

**Comment by MOMIN5** [comment]
yep, there isnt anything the main class either

**Comment by MOMIN5** [comment]
soon™

**Comment by goztb22** [comment]
try to compile when it will be ported
