### ISSUE TITLE
new readme  ok

### ISSUE THREAD

**Issue by goztb22** [MOMIN5/Phobos-1.16#4]
`# Phobos for 1.16

Phobos for 1.16 - Ported Phobos for fabric 1.16

## Usage

```bash
not out yet
```

## Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

![preview](https://i.ibb.co/tD3sDhX/222-1.png)`

**Comment by goztb22** [comment]
# Phobos for 1.16

Phobos for 1.16 - Ported Phobos for fabric 1.16

## Usage



```bash
not out yet
```



## Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.

![preview](https://i.ibb.co/tD3sDhX/222-1.png)

**Comment by MOMIN5** [comment]
can you pull request pls

**Comment by MOMIN5** [comment]
thanks i added it

**Comment by MOMIN5** [comment]
i also added your name in readme lol
